import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getPublicFounder } from "@/modules/founders/service";
import { EmptyState } from "@/components/directory/WebsiteList";
import { safeJsonLd } from "@/lib/seo/json-ld";
import { siteConfig } from "@/config/site";
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const profile = await getPublicFounder((await params).slug).catch(() => null);
  return profile ? { title: profile.name, description: profile.bio || `Explore websites by ${profile.name}.`, alternates: { canonical: `/founders/${profile.slug}` } } : { title: "Founder profile", robots: { index: false } };
}
export default async function FounderPage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ strategy?: string }> }) {
  const strategy = (await searchParams).strategy === "desktop" ? "desktop" : "mobile";
  const profile = await getPublicFounder((await params).slug, strategy);
  if (!profile) notFound();
  const { insights } = profile;
  const date = (value: string) => new Date(value).toISOString().slice(0,10);
  const summary = [["Measured websites", insights.measuredSites], ["Average latest score", insights.averageScore ?? "—"],
    ["Weekly overall wins", insights.weeklyWins], ["Best overall finish", insights.bestRank ? `#${insights.bestRank}` : "—"]];
  return <div className="page-shell mx-auto max-w-[960px]"><Link className="text-sm text-text-secondary hover:text-accent" href="/founders">← All founders</Link>
    <div className="mt-10 border-b border-border pb-10">{profile.avatarUrl && <Image unoptimized src={profile.avatarUrl} alt="" width={80} height={80} className="mb-5 h-20 w-20 rounded-full border border-border object-cover" />}<p className="page-eyebrow mb-4">Founder profile{profile.countryCode ? ` · ${profile.countryCode}` : ""}</p><h1 className="page-title">{profile.name}</h1>{profile.bio && <p className="page-description mt-5 whitespace-pre-line">{profile.bio}</p>}
      <div className="mt-6 flex flex-wrap gap-3">{profile.websiteUrl && <a href={profile.websiteUrl} className="button-secondary" target="_blank" rel="ugc noopener noreferrer">Website ↗</a>}{profile.socialLinks.map((link) => <a key={link.platform} href={link.url} className="button-secondary capitalize" target="_blank" rel="ugc noopener noreferrer">{link.platform} ↗</a>)}</div>
    </div>
    <section className="mt-10" aria-labelledby="founder-performance"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><h2 id="founder-performance" className="text-2xl font-medium tracking-tight">Performance at a glance</h2><nav aria-label="Founder performance device" className="flex gap-2">{(["mobile","desktop"] as const).map(device => <Link key={device} href={`?strategy=${device}`} aria-current={strategy===device?"page":undefined} className={`${strategy===device?"button-primary":"button-secondary"} capitalize`}>{device}</Link>)}</nav></div>
      <dl className="grid grid-cols-2 gap-5 border-y border-border py-6 sm:grid-cols-4">{summary.map(([label,value]) => <div key={label}><dt className="text-xs text-text-secondary">{label}</dt><dd className="mt-3 font-mono text-2xl">{value}</dd></div>)}</dl>
      <p className="mt-4 text-xs leading-relaxed text-text-muted">Latest complete {strategy} lab measurements, two samples per website. The average gives each measured website equal weight. Up to 100 currently public, active linked websites are shown. Historical or incomplete methods do not enter this summary. <Link href="/methodology" className="underline underline-offset-4">{insights.methodologyVersion} · {insights.rankingAlgorithmVersion}</Link></p>
      {insights.bestSite ? <div className="mt-6 border-l-2 border-accent pl-5"><p className="page-eyebrow">Best performing website</p><Link className="mt-2 inline-block text-xl font-medium hover:text-accent" href={`/site/${insights.bestSite.slug}?strategy=${strategy}`}>{insights.bestSite.name} ↗</Link><p className="mt-2 text-sm text-text-secondary">{insights.bestSite.score}/100 · measured {date(insights.bestSite.testedAt)} UTC</p></div> : <p className="mt-6 text-sm text-text-secondary">No complete measurements under the current method for this device yet. Historical results remain on individual website reports.</p>}
    </section>
    <h2 className="mt-10 mb-6 text-2xl font-medium tracking-tight">Published websites</h2>
    {!profile.sites.length ? <EmptyState title="More to come" description="This founder has not linked a public website yet." /> : <div className="divide-y divide-border">{profile.sites.map((site) => <Link href={`/site/${site.slug}`} key={site.id} className="flex items-center justify-between gap-4 py-6 text-lg hover:text-accent"><span>{site.name}</span><span className="text-sm text-text-muted">View website ↗</span></Link>)}</div>}
    <section className="mt-10" aria-labelledby="founder-technologies"><h2 id="founder-technologies" className="mb-5 text-2xl font-medium tracking-tight">Technologies</h2>{insights.technologies.length ? <div className="flex flex-wrap gap-2">{insights.technologies.map(technology => <Link key={technology.slug} className="button-secondary" href={`/technologies/${technology.slug}`}>{technology.name}</Link>)}</div> : <p className="text-sm text-text-secondary">No technologies have been attributed to these public websites yet.</p>}</section>
    <section className="mt-10" aria-labelledby="founder-improvements"><h2 id="founder-improvements" className="mb-5 text-2xl font-medium tracking-tight">Recently improved</h2><p className="mb-4 text-xs text-text-muted">Latest result in the past 30 days compared with the previous complete result for the same device and method.</p>{insights.recentlyImproved.length ? <ul className="divide-y divide-border">{insights.recentlyImproved.map(site => <li key={site.siteId} className="flex flex-wrap items-center justify-between gap-3 py-4"><Link className="hover:text-accent" href={`/site/${site.slug}?strategy=${strategy}`}>{site.name}</Link><span className="font-mono text-sm">{site.previousScore} → {site.score} <span className="text-green">(+{site.improvement} points)</span></span></li>)}</ul> : <p className="text-sm text-text-secondary">No comparable recent score increases for this device yet.</p>}</section>
    <section className="mt-10" aria-labelledby="founder-awards"><h2 id="founder-awards" className="mb-5 text-2xl font-medium tracking-tight">Earned badges</h2>{insights.awards.length ? <div className="grid gap-4 sm:grid-cols-2">{insights.awards.map(award => <article key={award.id} className="rounded-xl border border-border p-5"><h3 className="font-medium">{award.title}</h3><p className="mt-2 text-sm text-text-secondary">{award.description}</p><Link className="mt-3 inline-block text-sm hover:text-accent" href={`/site/${award.slug}?strategy=${strategy}`}>{award.name} ↗</Link><div className="mt-4 flex flex-wrap justify-between gap-3 text-xs text-text-muted"><span>{date(award.awardedAt)} UTC · {strategy}</span><a href={`/api/awards/${award.id}/share.png`} className="underline underline-offset-4">Share award</a></div></article>)}</div> : <p className="text-sm text-text-secondary">No earned badges are recorded for these websites on this device yet.</p>}</section>
    <section className="mt-10" aria-labelledby="founder-rankings"><h2 id="founder-rankings" className="mb-5 text-2xl font-medium tracking-tight">Ranking history</h2><p className="mb-4 text-xs text-text-muted">Up to 24 recent finalized placements. Weekly wins and best finish count overall competitions; collection placements are labeled separately.</p>{insights.rankings.length ? <div className="overflow-x-auto"><table className="w-full border-collapse text-left text-sm"><caption className="sr-only">Finalized {strategy} rankings for this founder&apos;s public websites</caption><thead className="border-b border-border text-xs text-text-secondary"><tr><th scope="col" className="py-3 pr-4">Period</th><th scope="col" className="px-3 py-3">Website</th><th scope="col" className="px-3 py-3">Collection</th><th scope="col" className="py-3 pl-3 text-right">Rank</th></tr></thead><tbody>{insights.rankings.map(row => <tr key={row.id} className="border-b border-border"><td className="whitespace-nowrap py-4 pr-4"><Link className="hover:text-accent" href={`/leaderboard?${new URLSearchParams({kind:row.kind,periodKey:row.periodKey,strategy,scope:row.scope,scopeKey:row.scopeKey})}`}>{row.periodKey}</Link></td><td className="px-3 py-4"><Link className="hover:text-accent" href={`/site/${row.slug}?strategy=${strategy}`}>{row.name}</Link></td><td className="px-3 py-4 text-text-secondary">{row.scope}{row.scopeKey?` · ${row.scopeKey}`:""}</td><td className="py-4 pl-3 text-right font-mono">#{row.rank}</td></tr>)}</tbody></table></div> : <p className="text-sm text-text-secondary">No finalized rankings for this device under the current competition method yet.</p>}</section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd({ "@context": "https://schema.org", "@type": "ProfilePage", url: `${siteConfig.url}/founders/${profile.slug}`, mainEntity: { "@type": "Person", name: profile.name, url: `${siteConfig.url}/founders/${profile.slug}`, image:profile.avatarUrl || undefined, description: profile.bio || undefined, sameAs: profile.socialLinks.map((link) => link.url) } }) }} />
  </div>;
}
