import Image from "next/image";
import Link from "next/link";
import type { getCompetitionOverview } from "@/modules/rankings/overview";
import type { RankingRow } from "@/modules/rankings/service";

type Archive = NonNullable<Awaited<ReturnType<typeof getCompetitionOverview>>>;
const siteName=(row:RankingRow)=>String(row.siteSnapshot.name??"Website");
const siteHref=(row:RankingRow)=>`/site/${String(row.siteSnapshot.slug??"")}`;

export function CompetitionArchive({data}:{data:Archive}) {
  const {period,strategy}=data;
  const rankingHref=(scope="overall",scopeKey="")=>`/leaderboard?${new URLSearchParams({kind:period.kind,periodKey:period.key,strategy,scope,scopeKey})}`;
  const date=(value:string)=>new Date(value).toISOString().slice(0,10);
  return <div className="page-shell mx-auto max-w-[1120px]">
    <Link href="/hall-of-fame" className="text-sm text-text-secondary hover:text-accent">← Hall of fame</Link>
    <header className="mt-8 border-b border-border pb-7"><p className="page-eyebrow">Finalized {period.kind} competition</p><h1 className="page-title mt-4">{period.key} · The results.</h1><p className="page-description mt-4">Recorded from {date(period.startAt)} to {date(period.endAt)} UTC. Positions and measurement evidence are preserved after the competition closes.</p>
      <nav aria-label="Archive device" className="mt-6 flex gap-2">{(["mobile","desktop"] as const).map(device=><Link key={device} href={`?strategy=${device}`} aria-current={strategy===device?"page":undefined} className={`${device===strategy?"button-primary":"button-secondary"} capitalize`}>{device}</Link>)}</nav>
    </header>
    <p className="my-5 text-xs leading-relaxed text-text-muted">{strategy} lab results · {period.method} · {period.algorithm}. Private or removed listings are hidden at read time; retained positions are never renumbered. <Link className="underline underline-offset-4" href="/methodology">Ranking methodology</Link></p>
    <dl className="grid grid-cols-2 gap-5 border-y border-border py-6 sm:grid-cols-4">{[["Published finalists",data.stats.finalists],["Average finalist score",data.stats.averageScore??"—"],["Country winners",data.stats.countries],["Technology winners",data.stats.technologies]].map(([label,value])=><div key={label}><dt className="text-xs text-text-secondary">{label}</dt><dd className="mt-3 font-mono text-2xl">{value}</dd></div>)}</dl><p className="mt-3 text-xs text-text-muted">Statistics describe currently visible entries in the preserved overall top 100 for this device, and visible collection winners.</p>
    <section className="mt-9 border-l-2 border-accent pl-5"><p className="page-eyebrow">Overall winner</p>{data.winner?<><h2 className="mt-3 text-3xl font-medium"><Link href={siteHref(data.winner)} className="hover:text-accent">{siteName(data.winner)} ↗</Link></h2><p className="mt-3 font-mono text-lg">#1 · {data.winner.score}/100</p></>:<><h2 className="mt-3 text-xl font-medium">No public winner available</h2><p className="mt-2 text-sm text-text-secondary">This period has no published #1 for this device. A hidden entry does not promote another website.</p></>}</section>
    <section className="mt-10"><div className="mb-5 flex items-center justify-between gap-4"><h2 className="text-2xl font-medium">The top ten</h2><Link className="text-sm underline underline-offset-4" href={rankingHref()}>Full top 100</Link></div>{data.top.length?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Finalized {strategy} overall results for {period.key}</caption><thead className="border-b border-border text-xs text-text-secondary"><tr><th scope="col" className="py-3 pr-3">Rank</th><th scope="col" className="px-3 py-3">Website</th><th scope="col" className="px-3 py-3 text-right">Score</th><th scope="col" className="py-3 pl-3 text-right">LCP</th></tr></thead><tbody>{data.top.map(row=><tr key={row.siteId} className="border-b border-border"><td className="py-4 pr-3 font-mono">#{row.rank}</td><td className="px-3 py-4"><Link href={siteHref(row)} className="hover:text-accent">{siteName(row)}</Link></td><td className="px-3 py-4 text-right font-mono">{row.score}</td><td className="py-4 pl-3 text-right font-mono">{row.lcpMs===null?"—":`${(row.lcpMs/1000).toFixed(2)}s`}</td></tr>)}</tbody></table></div>:<p className="text-sm text-text-secondary">No visible finalists are recorded for this device.</p>}</section>
    <div className="mt-10 grid gap-9 md:grid-cols-2"><section><h2 className="mb-5 text-2xl font-medium">Biggest improvements</h2><ArchiveEntries rows={data.improved} improvement /><Link className="mt-4 inline-block text-sm underline underline-offset-4" href={rankingHref("improved")}>All improvement results</Link></section><section><h2 className="mb-5 text-2xl font-medium">New entries</h2><ArchiveEntries rows={data.newcomers}/><Link className="mt-4 inline-block text-sm underline underline-offset-4" href={rankingHref("newcomer")}>All newcomer results</Link></section></div>
    <section className="mt-10"><h2 className="mb-5 text-2xl font-medium">Collection winners</h2><div className="grid gap-8 md:grid-cols-3">{(["country","category","technology"] as const).map(scope=><div key={scope}><h3 className="mb-3 text-lg font-medium capitalize">{scope}</h3>{data.collections.filter(row=>row.scope===scope).length?<ul className="divide-y divide-border">{data.collections.filter(row=>row.scope===scope).map(row=><li key={row.id} className="py-4"><Link href={rankingHref(scope,row.scopeKey)} className="text-xs text-text-muted underline underline-offset-4">{row.scopeKey}</Link><Link href={`/site/${row.slug}`} className="mt-2 block text-sm hover:text-accent">{row.name} ↗</Link><p className="mt-1 font-mono text-xs">#1 · {row.score}/100</p></li>)}</ul>:<p className="text-sm text-text-secondary">No public winner for this collection.</p>}</div>)}</div><p className="mt-4 text-xs text-text-muted">Up to 12 winners per collection type are shown. Individual collection links open their preserved results.</p></section>
    <section className="mt-10"><h2 className="mb-5 text-2xl font-medium">Captured during this competition</h2>{data.captures.length?<div className="grid gap-5 sm:grid-cols-3">{data.captures.map(capture=><figure key={capture.id}><a href={capture.url} target="_blank" rel="noopener noreferrer"><Image unoptimized loading="lazy" src={capture.url} alt={`${capture.name} ${strategy} screenshot during ${period.key}`} width={capture.width} height={capture.height} className="aspect-[4/3] w-full rounded-lg border border-border object-cover object-top"/></a><figcaption className="mt-2 text-xs text-text-muted">#{capture.rank} · {capture.name} · {date(capture.capturedAt)} UTC</figcaption></figure>)}</div>:<p className="text-sm text-text-secondary">No retained {strategy} captures from this period for the overall top three. Later images are not substituted for historical evidence.</p>}</section>
    <section className="mt-10"><h2 className="mb-5 text-2xl font-medium">Achievement share cards</h2>{data.awards.length?<ul className="grid gap-4 sm:grid-cols-2">{data.awards.map(award=><li key={award.id} className="border-t border-border pt-4"><p className="font-medium">{award.title}</p><p className="mt-2 text-sm text-text-secondary">{award.name}</p><a className="mt-3 inline-block text-sm underline underline-offset-4" href={`/api/awards/${award.id}/share.png`}>Open share card ↗</a></li>)}</ul>:<p className="text-sm text-text-secondary">No earned achievement cards have been recorded for this period and device yet.</p>}</section>
  </div>;
}
function ArchiveEntries({rows,improvement=false}:{rows:RankingRow[];improvement?:boolean}){
  return rows.length?<ol className="divide-y divide-border">{rows.map(row=><li key={row.siteId} className="flex items-start justify-between gap-4 py-4"><Link href={siteHref(row)} className="text-sm hover:text-accent">#{row.rank} · {siteName(row)}</Link><span className="shrink-0 font-mono text-sm">{improvement&&typeof row.evidence.improvement==="number"?`+${row.evidence.improvement} points`:`${row.score}/100`}</span></li>)}</ol>:<p className="text-sm text-text-secondary">No eligible published entries for this selection.</p>;
}
