import { sites, adSlots } from "./schema";

// Seed data from prototype — 20 websites
export const seedSites: (typeof sites.$inferInsert)[] = [
  { slug: "linear-app", name: "Linear", url: "https://linear.app", description: "Issue tracking built for speed", ownerName: "Karri Saarinen", currentScore: 99, currentLoadTime: "0.4s", currentFcp: "0.3s", currentLcp: "0.6s", currentCls: "0.001", currentTbt: "12ms", currentTti: "0.5s", currentSi: "0.4s", trend: 2, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=linear.app&sz=64" },
  { slug: "vercel", name: "Vercel", url: "https://vercel.com", description: "Frontend cloud for the modern web", ownerName: "Guillermo Rauch", currentScore: 98, currentLoadTime: "0.5s", currentFcp: "0.4s", currentLcp: "0.7s", currentCls: "0.003", currentTbt: "15ms", currentTti: "0.6s", currentSi: "0.5s", trend: 1, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=vercel.com&sz=64" },
  { slug: "cloudflare", name: "Cloudflare", url: "https://cloudflare.com", description: "Global CDN & security platform", ownerName: "Matthew Prince", currentScore: 98, currentLoadTime: "0.5s", currentFcp: "0.3s", currentLcp: "0.8s", currentCls: "0.002", currentTbt: "10ms", currentTti: "0.7s", currentSi: "0.5s", trend: 3, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=cloudflare.com&sz=64" },
  { slug: "stripe-docs", name: "Stripe Docs", url: "https://stripe.com", description: "Payment infrastructure documentation", ownerName: "Patrick Collison", currentScore: 97, currentLoadTime: "0.6s", currentFcp: "0.5s", currentLcp: "0.9s", currentCls: "0.004", currentTbt: "18ms", currentTti: "0.8s", currentSi: "0.6s", trend: -1, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=stripe.com&sz=64" },
  { slug: "astro", name: "Astro", url: "https://astro.build", description: "The web framework for content sites", ownerName: "Fred K. Schott", currentScore: 97, currentLoadTime: "0.6s", currentFcp: "0.4s", currentLcp: "0.8s", currentCls: "0.001", currentTbt: "14ms", currentTti: "0.7s", currentSi: "0.5s", trend: 5, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=astro.build&sz=64" },
  { slug: "svelte", name: "Svelte", url: "https://svelte.dev", description: "Cybernetically enhanced web apps", ownerName: "Rich Harris", currentScore: 96, currentLoadTime: "0.7s", currentFcp: "0.5s", currentLcp: "0.9s", currentCls: "0.002", currentTbt: "16ms", currentTti: "0.8s", currentSi: "0.6s", trend: 2, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=svelte.dev&sz=64" },
  { slug: "turso", name: "Turso", url: "https://turso.tech", description: "Edge-hosted distributed database", ownerName: "Glauber Costa", currentScore: 96, currentLoadTime: "0.7s", currentFcp: "0.6s", currentLcp: "1.0s", currentCls: "0.005", currentTbt: "20ms", currentTti: "0.9s", currentSi: "0.7s", trend: -2, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=turso.tech&sz=64" },
  { slug: "hono", name: "Hono", url: "https://hono.dev", description: "Ultrafast web framework for the edge", ownerName: "Yusuke Wada", currentScore: 95, currentLoadTime: "0.7s", currentFcp: "0.5s", currentLcp: "0.9s", currentCls: "0.001", currentTbt: "12ms", currentTti: "0.7s", currentSi: "0.6s", trend: 8, countryFlag: "🇯🇵", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=hono.dev&sz=64" },
  { slug: "fly-io", name: "Fly.io", url: "https://fly.io", description: "Run your full-stack apps globally", ownerName: "Kurt Mackey", currentScore: 95, currentLoadTime: "0.8s", currentFcp: "0.6s", currentLcp: "1.0s", currentCls: "0.003", currentTbt: "22ms", currentTti: "0.9s", currentSi: "0.7s", trend: 1, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=fly.io&sz=64" },
  { slug: "bun", name: "Bun", url: "https://bun.sh", description: "Incredibly fast JavaScript runtime", ownerName: "Jarred Sumner", currentScore: 94, currentLoadTime: "0.8s", currentFcp: "0.7s", currentLcp: "1.1s", currentCls: "0.002", currentTbt: "18ms", currentTti: "1.0s", currentSi: "0.8s", trend: 4, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=bun.sh&sz=64" },
  { slug: "railway", name: "Railway", url: "https://railway.app", description: "Infrastructure, instantly", ownerName: "Jake Cooper", currentScore: 94, currentLoadTime: "0.9s", currentFcp: "0.7s", currentLcp: "1.1s", currentCls: "0.004", currentTbt: "24ms", currentTti: "1.0s", currentSi: "0.8s", trend: 3, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=railway.app&sz=64" },
  { slug: "resend", name: "Resend", url: "https://resend.com", description: "Email for developers", ownerName: "Zeno Rocha", currentScore: 93, currentLoadTime: "0.9s", currentFcp: "0.8s", currentLcp: "1.2s", currentCls: "0.003", currentTbt: "20ms", currentTti: "1.1s", currentSi: "0.9s", trend: -1, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=resend.com&sz=64" },
  { slug: "deno", name: "Deno", url: "https://deno.com", description: "The easiest, most secure JS runtime", ownerName: "Ryan Dahl", currentScore: 93, currentLoadTime: "0.9s", currentFcp: "0.7s", currentLcp: "1.1s", currentCls: "0.002", currentTbt: "22ms", currentTti: "1.0s", currentSi: "0.8s", trend: 2, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=deno.com&sz=64" },
  { slug: "planetscale", name: "Planetscale", url: "https://planetscale.com", description: "Serverless MySQL platform", ownerName: "Sam Lambert", currentScore: 92, currentLoadTime: "1.0s", currentFcp: "0.8s", currentLcp: "1.2s", currentCls: "0.005", currentTbt: "26ms", currentTti: "1.2s", currentSi: "1.0s", trend: -3, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=planetscale.com&sz=64" },
  { slug: "supabase", name: "Supabase", url: "https://supabase.com", description: "Open source Firebase alternative", ownerName: "Paul Copplestone", currentScore: 92, currentLoadTime: "1.0s", currentFcp: "0.9s", currentLcp: "1.3s", currentCls: "0.006", currentTbt: "28ms", currentTti: "1.2s", currentSi: "1.0s", trend: 1, countryFlag: "🇸🇬", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=supabase.com&sz=64" },
  { slug: "tailwind-css", name: "Tailwind CSS", url: "https://tailwindcss.com", description: "Utility-first CSS framework", ownerName: "Adam Wathan", currentScore: 91, currentLoadTime: "1.0s", currentFcp: "0.8s", currentLcp: "1.2s", currentCls: "0.002", currentTbt: "20ms", currentTti: "1.1s", currentSi: "0.9s", trend: 0, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=tailwindcss.com&sz=64" },
  { slug: "remix", name: "Remix", url: "https://remix.run", description: "Full stack web framework", ownerName: "Michael Jackson", currentScore: 91, currentLoadTime: "1.1s", currentFcp: "0.9s", currentLcp: "1.3s", currentCls: "0.004", currentTbt: "24ms", currentTti: "1.2s", currentSi: "1.0s", trend: -2, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=remix.run&sz=64" },
  { slug: "neon", name: "Neon", url: "https://neon.tech", description: "Serverless Postgres database", ownerName: "Nikita Shamgunov", currentScore: 90, currentLoadTime: "1.1s", currentFcp: "0.9s", currentLcp: "1.4s", currentCls: "0.003", currentTbt: "26ms", currentTti: "1.3s", currentSi: "1.1s", trend: 5, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=neon.tech&sz=64" },
  { slug: "clerk", name: "Clerk", url: "https://clerk.com", description: "Drop-in auth & user management", ownerName: "Colin Sidoti", currentScore: 90, currentLoadTime: "1.1s", currentFcp: "1.0s", currentLcp: "1.4s", currentCls: "0.005", currentTbt: "30ms", currentTti: "1.3s", currentSi: "1.1s", trend: 1, countryFlag: "🇺🇸", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=clerk.com&sz=64" },
  { slug: "drizzle", name: "Drizzle", url: "https://orm.drizzle.team", description: "TypeScript ORM that's blazingly fast", ownerName: "Alex Blokh", currentScore: 89, currentLoadTime: "1.2s", currentFcp: "1.0s", currentLcp: "1.5s", currentCls: "0.002", currentTbt: "22ms", currentTti: "1.3s", currentSi: "1.1s", trend: 7, countryFlag: "🇺🇦", tier: "pro", isListed: true, faviconUrl: "https://www.google.com/s2/favicons?domain=orm.drizzle.team&sz=64" },
];

// Ad slots are now dynamically created via Polar subscriptions
// No seed data needed — empty slots show "Advertise" CTA
export const seedAdSlots: (typeof adSlots.$inferInsert)[] = [];
