import type { Metadata } from "next";
import Link from "next/link";
import { EditorialPage } from "@/components/layout/EditorialPage";
export const metadata: Metadata = { title: "How we measure website performance", description: "Two PageSpeed Insights lab samples per device, transparent tie-breaks and preserved weekly results. Read the TheFastestWeb methodology.", alternates: { canonical: "/methodology" } };
export default function Page() {
  return <EditorialPage eyebrow="The measurement standard" title="Speed deserves context." intro="A performance score is a useful signal. Understanding how it was measured makes it a useful comparison.">
    <section><h2>Two samples. Two separate devices.</h2><p>The current method, psi-v2-two-sample, runs two Google PageSpeed Insights lab tests for each selected device strategy. Mobile and desktop are measured separately. We average the two scores and each numeric metric; for two samples, that mean is also their median. Both samples must complete before a result can be saved.</p><p>Times are recorded in milliseconds and scores are rounded to the nearest whole number. If either sample lacks time to interactive, that metric remains unavailable. Failed tests do not become zero scores.</p></section>
    <section><h2>Lab performance is not field performance.</h2><p>These are Lighthouse lab measurements from PageSpeed Insights. They describe a simulated visit and can vary with server load, network conditions, content and the upstream testing environment. They are not a Core Web Vitals assessment from real users. Total blocking time is a lab diagnostic, not interaction to next paint.</p><p>Use the results to investigate changes and compare measurements taken with the same method. A high score does not guarantee a particular experience for every visitor.</p></section>
    <section><h2>A repeatable order.</h2><p>Weekly and monthly rankings use the latest eligible measurement during the period. All-time rankings use each website’s best eligible result. The current ranking-v1 algorithm orders by performance score, then lower largest contentful paint, lower cumulative layout shift, lower total blocking time and finally a stable website ID.</p><p>Most improved compares the current result with the latest eligible result before the period. Newcomers are websites added during that period. Mobile and desktop results always remain separate.</p></section>
    <section><h2>One calendar, preserved results.</h2><p>Weeks start on Monday at 00:00 UTC and end the following Monday. Months use UTC calendar boundaries. Once a competition closes, its results and the evidence behind them are preserved. The archive retains up to the top 100 websites in each device and collection.</p></section>
    <section><h2>Historical results keep their history.</h2><p>Measurements from earlier versions remain available on website reports and in the directory. They do not qualify for the new standardized competitions. The report identifies the method, device, sample count and measurement time so that different kinds of data are not silently combined.</p><p>The directory’s latest recorded mobile score may be older than the current competition. Always check the report date before interpreting it as a website’s present performance.</p></section>
    <section><h2>Your website can change.</h2><p>Outages, redirects and missing badges are tracked as separate states. A temporary network error does not erase past measurements or create a successful test. Scheduled monitoring depends on availability, your plan and the shared provider budget.</p><p><Link href="/leaderboard">Explore the rankings</Link> or <Link href="/test">measure your website</Link>.</p></section>
  </EditorialPage>;
}
