import Link from "next/link";
import { CheckoutButton } from "@/app/dashboard/controls";
import type { listProducts } from "@/modules/payments/service";

export function PricingTiers({ products, signedIn, sites, adInventory }: {
  products: Awaited<ReturnType<typeof listProducts>>; signedIn: boolean; sites: { id: string; name: string }[]; adInventory: { id: string; position: string; orderIndex: number }[];
}) {
  return <div className="grid items-start gap-6 lg:grid-cols-2">
    <article className="rounded-xl border border-border bg-bg-main p-7"><p className="page-eyebrow">Start with evidence</p><h2 className="mt-3 text-2xl font-semibold">Free directory listing</h2><p className="mt-4 text-4xl font-semibold tracking-tight">Free</p><p className="mt-4 text-sm leading-relaxed text-text-secondary">Submit a website for a verified performance measurement, public profile and fair rankings.</p><ul className="my-6 space-y-3 text-sm text-text-secondary"><li>Server-verified performance evidence</li><li>Public website profile and leaderboard eligibility</li><li>Ownership verification and founder profile</li><li>Badge eligibility and transparent ranking methodology</li></ul><Link href="/submit" className="button-primary">Submit a website</Link></article>
    {products.map((product) => { const formatter = new Intl.NumberFormat("en", { style: "currency", currency: product.currency }); const price = formatter.format(product.amountCents / 10 ** (formatter.resolvedOptions().maximumFractionDigits ?? 2)); return <article key={product.key} className="rounded-xl border border-border bg-bg-card p-7"><p className="page-eyebrow">{product.kind.replaceAll("_", " ")}</p><h2 className="mt-3 text-2xl font-semibold">{product.title}</h2><p className="mt-4 text-4xl font-semibold tracking-tight">{price}</p><p className="mt-2 text-sm text-text-muted">{product.billingInterval === "one_time" ? "One-time payment" : `Billed every ${product.billingInterval}`} · Before applicable tax</p><p className="mt-5 text-sm text-text-secondary">{product.requiresSite ? "Access applies to the owned website you select." : "Access applies to your account."} {product.entitlementDays ? `Configured access duration: ${product.entitlementDays} days.` : product.billingInterval === "one_time" ? "No fixed access expiry is configured." : "Access follows your active subscription period."}</p>{signedIn ? <CheckoutButton productKey={product.key} requiresSite={product.requiresSite} sites={sites} adInventory={product.kind === "sidebar_ad" ? adInventory : undefined} /> : <Link className="button-primary mt-6" href="/auth/login?returnTo=%2Fpricing">Sign in to choose this plan</Link>}</article>; })}
    {!products.length && <article className="rounded-xl border border-dashed border-border p-7"><p className="page-eyebrow">Paid access</p><h2 className="mt-3 text-2xl font-semibold">New plans are being prepared.</h2><p className="mt-4 text-sm leading-relaxed text-text-secondary">Purchases become available when the approved product catalog and payment account are connected. Existing memberships and historical entitlements remain preserved.</p><Link href="/dashboard" className="button-secondary mt-6">View existing access</Link></article>}
  </div>;
}
