"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { AdminAction } from "@/modules/admin/service";
import { FormSection, FormStatus, PreviewBoard, checkbox, field, label, primaryButton, secondaryButton, toggleRow } from "./form-ui";

export default function InventoryForm() {
  const router = useRouter(), [preview, setPreview] = useState<{ token: string; proposed: AdminAction; before: unknown } | null>(null), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [failed, setFailed] = useState(false);
  return <FormSection title="Configure ad inventory" detail="Add only placements the site actually renders. Existing coordinates cannot be moved. Disabling inventory stops new holds; existing paid placements retain their recorded lifecycle.">
    <form onSubmit={async (event) => { event.preventDefault(); setBusy(true); setMessage(""); setFailed(false); const form = new FormData(event.currentTarget);
      const action = preview?.proposed ?? { action: "ad.inventory", inventoryId: form.get("id") || crypto.randomUUID(), position: form.get("position"), orderIndex: Number(form.get("orderIndex")), active: form.has("active"), reason: form.get("reason") };
      try { const response = await fetch("/api/admin/actions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ operation: preview ? "confirm" : "preview", action, ...(preview ? { token: preview.token } : {}) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); if (preview) { setPreview(null); setMessage(`Inventory saved. Audit ${result.auditId}.`); router.refresh(); } else setPreview(result); }
      catch (error) { setFailed(true); setMessage(error instanceof Error ? error.message : "Inventory could not be saved."); } finally { setBusy(false); } }}>
      <fieldset disabled={busy || Boolean(preview)} className="grid min-w-0 gap-x-5 gap-y-5 sm:grid-cols-2"><label className={label}>Existing inventory UUID<input className={field} name="id" placeholder="Empty creates a new placement" /></label><label className={label}>Position<select name="position" className={field}><option value="left">Left sidebar</option><option value="right">Right sidebar</option></select></label><label className={label}>Order index<input name="orderIndex" type="number" min={0} max={100} step={1} required className={field} /></label><div className="self-end"><label className={toggleRow}>Accept new reservations<input className={checkbox} name="active" type="checkbox" /></label></div><label className={`${label} sm:col-span-2`}>Reason<textarea className={`${field} min-h-28 leading-relaxed`} name="reason" minLength={8} maxLength={500} required /></label></fieldset>
      {preview && <PreviewBoard value={{ before: preview.before, proposed: preview.proposed }} />}<div className="mt-7 flex flex-wrap gap-3"><button className={primaryButton} disabled={busy}>{preview ? "Confirm inventory change" : "Preview inventory change"}</button>{preview && <button className={secondaryButton} type="button" onClick={() => setPreview(null)}>Discard preview</button>}</div><FormStatus message={message} failed={failed} /></form></FormSection>;
}
