"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { AdminAction } from "@/modules/admin/service";

export default function InventoryForm() {
  const router = useRouter(), [preview, setPreview] = useState<{ token: string; proposed: AdminAction; before: unknown } | null>(null), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  return <section className="mt-8 rounded-xl border border-border bg-bg-card p-6"><h2 className="text-xl font-semibold">Configure ad inventory</h2><p className="mt-3 text-sm text-text-secondary">Add only placements the site actually renders. Existing coordinates cannot be moved. Disabling inventory stops new holds; existing paid placements retain their recorded lifecycle.</p>
    <form className="mt-5" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setMessage(""); const form = new FormData(event.currentTarget);
      const action = preview?.proposed ?? { action: "ad.inventory", inventoryId: form.get("id") || crypto.randomUUID(), position: form.get("position"), orderIndex: Number(form.get("orderIndex")), active: form.has("active"), reason: form.get("reason") };
      try { const response = await fetch("/api/admin/actions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ operation: preview ? "confirm" : "preview", action, ...(preview ? { token: preview.token } : {}) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); if (preview) { setPreview(null); setMessage(`Inventory saved. Audit ${result.auditId}.`); router.refresh(); } else setPreview(result); }
      catch (error) { setMessage(error instanceof Error ? error.message : "Inventory could not be saved."); } finally { setBusy(false); } }}>
      <fieldset disabled={busy || Boolean(preview)} className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Existing inventory UUID<input className="form-field mt-2" name="id" placeholder="Empty creates a new placement" /></label><label className="text-sm">Position<select name="position" className="form-field mt-2"><option value="left">Left sidebar</option><option value="right">Right sidebar</option></select></label><label className="text-sm">Order index<input name="orderIndex" type="number" min={0} max={100} step={1} required className="form-field mt-2" /></label><label className="flex items-center gap-3 text-sm"><input name="active" type="checkbox" />Accept new reservations</label><label className="text-sm sm:col-span-2">Reason<textarea className="form-field mt-2" name="reason" minLength={8} maxLength={500} required /></label></fieldset>
      {preview && <pre className="mt-5 overflow-auto border border-border p-4 text-xs">{JSON.stringify({ before: preview.before, proposed: preview.proposed }, null, 2)}</pre>}<div className="mt-5 flex gap-3"><button className="button-primary" disabled={busy}>{preview ? "Confirm inventory change" : "Preview inventory change"}</button>{preview && <button className="button-secondary" type="button" onClick={() => setPreview(null)}>Discard preview</button>}</div><p role="status" className="mt-3 text-sm">{message}</p></form></section>;
}
