import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { siteConfig } from "@/config/site";
import { getDashboard } from "@/modules/dashboard/queries";
import { getOwnFounder } from "@/modules/founders/service";
import { getCatalog } from "@/modules/catalog/service";
import { listAvailableAdInventory } from "@/modules/payments/ads";
import { isPaymentsEnabled } from "@/infrastructure/payments/dodo";
import { listProducts } from "@/modules/payments/service";
import { getNotificationPreferences } from "@/modules/notifications/service";
import { notificationTemplates, templateSchema } from "@/modules/notifications/templates";
import { CheckoutButton, FounderForm, NotificationRead, PreferencesForm, RetestButton } from "./controls";

export const metadata: Metadata = { title: "Your dashboard", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ siteCursor?: string }> }) {
  const user = await getCurrentUser();
  if (!user) {
    if (siteConfig.isDemo) return <main className="page-shell"><p className="page-eyebrow">Account workspace</p><h1 className="page-title mt-3">Your websites, in one place.</h1><p className="page-description mt-5">The account workspace brings together performance history, rankings, ownership claims, purchases and email preferences. Sign-in is disabled in this public demo while the final Google OAuth domain is configured.</p><Link href="/" className="button-primary mt-8">Explore the directory</Link></main>;
    redirect("/auth/login?returnTo=%2Fdashboard");
  }
  const { siteCursor } = await searchParams;
  const [data, profile, catalog, preferences, products, adInventory] = await Promise.all([getDashboard(user.id, siteCursor), getOwnFounder(user.id), getCatalog(), getNotificationPreferences(user.id), listProducts(), isPaymentsEnabled() ? listAvailableAdInventory() : Promise.resolve([])]);
  return <main className="page-shell"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="page-eyebrow">Your workspace</p><h1 className="page-title mt-3">Welcome, {user.name.split(" ")[0]}.</h1><p className="page-description mt-4">Keep your websites fast, verified and ready for the next ranking.</p></div><Link href="/submit" className="button-primary">Add a website</Link></div>
    <div className="my-8 grid grid-cols-2 gap-4 lg:grid-cols-4">{[["Owned websites", data.totals.websites], ["Current access grants", data.totals.grants], ["Unread notifications", data.totals.unread], ["Pending claims", data.totals.claims]].map(([label, value]) => <div key={label} className="border-t border-border py-5"><p className="text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-text-muted">{label}</p></div>)}</div>
    <Section title="My websites" detail="Latest measurements from the shared daily monitoring schedule.">{data.ownedSites.length ? <div className="divide-y divide-border">{data.ownedSites.map((site) => <article key={site.id} className="grid gap-4 py-5 sm:grid-cols-[1fr_auto]"><div><Link className="text-lg font-semibold no-underline hover:underline" href={`/sites/${site.slug}`}>{site.name}</Link><p className="mt-2 text-sm text-text-secondary">{site.lifecycle} · {site.isPro ? "PRO · Badge exempt" : `Badge ${site.badgeStatus.replaceAll("_", " ")}`} · {site.monitoringPaused ? "Monitoring paused" : "Monitoring enabled"}</p><p className="mt-1 text-xs text-text-muted">{site.lastTestedAt ? `Last measured ${site.lastTestedAt.toLocaleString("en-GB", { timeZone: "UTC" })} UTC` : "No verified measurement yet"}</p></div><div className="flex items-start gap-6"><div className="text-right"><p className="font-mono text-3xl">{site.lastTestedAt ? site.score : "—"}</p><p className="text-xs text-text-muted">Performance / 100</p></div><RetestButton slug={site.slug} /></div></article>)}</div> : <Empty>No websites yet. Add a website or verify a claim to start monitoring.</Empty>}</Section>
    <div className="mt-8 grid gap-8 xl:grid-cols-2"><Section title="Rankings and awards" detail="Finalized results with published measurement evidence.">{data.rankings.length ? <ul className="divide-y divide-border">{data.rankings.map((rank, index) => <li key={`${rank.period}-${rank.scope}-${index}`} className="py-3 text-sm"><span className="font-mono text-accent">#{rank.rank}</span> {rank.siteName}<span className="mt-1 block text-xs text-text-muted">{rank.period} · {rank.scope}{rank.scopeKey ? ` / ${rank.scopeKey}` : ""} · {rank.score.toFixed(1)} points</span></li>)}</ul> : <Empty>No finalized rankings yet.</Empty>}{data.awards.map((award, index) => <p key={index} className="mt-3 text-sm">🏅 {award.title} · {award.siteName}</p>)}</Section>
      <Section title="Notifications" detail="Recent account, monitoring and competition updates.">{data.messages.length ? <ul className="divide-y divide-border">{data.messages.map((message) => { const template = templateSchema.safeParse(message.type); return <li key={message.id} className="flex justify-between gap-4 py-3"><div><p className="text-sm">{template.success ? notificationTemplates[template.data].subject : message.type.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-text-muted">{message.createdAt.toLocaleDateString("en-GB")}</p></div>{!message.readAt && <NotificationRead id={message.id} />}</li>; })}</ul> : <Empty>No notifications yet.</Empty>}</Section></div>
    <div className="mt-8 grid gap-8 xl:grid-cols-2"><Section title="Current plan and purchases" detail="Your entitlement history remains independent of website status.">{data.grants.length ? <ul className="space-y-3">{data.grants.map((grant) => <li key={grant.id} className="text-sm"><strong>{grant.kind.replaceAll("_", " ")}</strong> · {grant.source === "legacy" ? "Preserved existing access" : "Dodo purchase"}<span className="ml-2 text-xs text-text-muted">{grant.endsAt ? `Until ${grant.endsAt.toLocaleDateString("en-GB")}` : "No fixed expiry"}</span></li>)}</ul> : <Empty>No paid access is active.</Empty>}
      {data.orders.length > 0 && <div className="mt-5 border-t border-border pt-4"><h3 className="text-sm font-semibold">Recent checkouts</h3>{data.orders.map((order) => <p className="mt-3 text-sm" key={order.id}>{order.title} · <span className="font-mono">{order.status}</span>{["creating", "uncertain"].includes(order.status) && <span className="mt-1 block text-xs text-text-muted">This checkout needs reconciliation. Do not repeat the purchase.</span>}</p>)}</div>}
      {data.payments.map((payment) => <p className="mt-3 text-sm" key={payment.id}>{formatMoney(payment.amountCents, payment.currency)} · {payment.status} · {payment.occurredAt.toLocaleDateString("en-GB")}</p>)}
    </Section><Section title="Email preferences" detail="Choose optional updates. Marketing is off unless you enable it."><PreferencesForm initial={preferences} /></Section></div>
    <div className="mt-8"><Section title="Ownership claims" detail="Verification proves domain control. Existing ownership transfers require review.">{data.claims.length ? <ul className="space-y-3">{data.claims.map((claim) => <li key={claim.id} className="text-sm"><span className="font-mono">{claim.id}</span><p className="mt-1 text-text-secondary">{claim.method.replaceAll("_", " ")} · {claim.status} · Expires {claim.expiresAt.toLocaleDateString("en-GB")}</p></li>)}</ul> : <Empty>You have no ownership claims. Start a claim from a website page.</Empty>}</Section></div>
    {data.screenshots.length > 0 && <div className="mt-8"><Section title="Recent screenshots" detail="Latest retained public captures of your websites."><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{data.screenshots.filter((capture) => capture.publicUrl.startsWith("https://")).map((capture, index) => <a href={capture.publicUrl} target="_blank" rel="noopener noreferrer" key={index} className="block no-underline"><Image src={capture.publicUrl} alt={`${capture.siteName} ${capture.device} screenshot`} width={640} height={400} unoptimized className="aspect-[8/5] w-full rounded-lg border border-border object-cover object-top" /><p className="mt-2 text-sm">{capture.siteName} · {capture.device}</p><p className="text-xs text-text-muted">{capture.capturedAt.toLocaleDateString("en-GB")}</p></a>)}</div></Section></div>}
    <div className="mt-8"><Section title="Founder profile" detail="Your profile stays private until you choose to publish it."><FounderForm initial={profile} name={user.name} countries={catalog.countries} sites={data.ownedSites} /></Section></div>
    <div className="mt-8"><Section title="Available plans" detail="Server-verified products and prices. Checkout alone does not grant access.">{products.length ? <div className="grid gap-6 md:grid-cols-2">{products.map((product) => <article key={product.key} className="border-t border-border pt-4"><h3 className="text-lg font-semibold">{product.title}</h3><p className="mt-2 text-text-secondary">{formatMoney(product.amountCents, product.currency)}{product.billingInterval !== "one_time" ? ` / ${product.billingInterval}` : " one time"} <span className="text-xs">before applicable tax</span></p><CheckoutButton productKey={product.key} requiresSite={product.requiresSite} sites={data.ownedSites} adInventory={product.kind === "sidebar_ad" ? adInventory : undefined} /></article>)}</div> : <Empty>New purchases are currently unavailable. Existing access remains visible above.</Empty>}</Section></div>
    {data.advertisements.length > 0 && <div className="mt-8"><Section title="Ad placements" detail="Paid creative is reviewed before publication. Held checkout capacity remains reserved until the provider outcome is reconciled."><ul className="space-y-4">{data.advertisements.map((ad) => <li key={ad.id} className="text-sm"><strong className="capitalize">{ad.position} sidebar · position {ad.orderIndex}</strong><span className="ml-3 font-mono">{ad.status}</span><p className="mt-1 text-xs text-text-muted">{ad.endsAt ? `Publication window ends ${ad.endsAt.toLocaleString("en-GB", { timeZone: "UTC" })} UTC` : ad.status === "paid" ? "Payment confirmed; creative review is pending. The purchased duration begins at approval." : ad.status === "held" ? "Checkout is pending or needs reconciliation. Do not start another purchase for this placement." : "No active publication window."}</p></li>)}</ul></Section></div>}
    {data.nextSiteCursor && <Link className="button-secondary mt-8" href={`/dashboard?siteCursor=${data.nextSiteCursor}`}>Next 50 websites</Link>}
    {siteCursor && <Link className="button-secondary ml-3 mt-8" href="/dashboard">First website page</Link>}
    <p className="mt-8 text-xs text-text-muted">This workspace shows 50 websites per page, up to 100 current access grants and the latest 30 account events. Totals include all matching records. Payment and ranking summaries use application records, not third-party analytics estimates.</p>
  </main>;
}
function Section({ title, detail, children }: { title: string; detail: string; children: React.ReactNode }) { return <section className="h-full rounded-xl border border-border bg-bg-main p-6"><h2 className="text-xl font-semibold tracking-tight">{title}</h2><p className="mb-5 mt-2 text-sm text-text-muted">{detail}</p>{children}</section>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="py-4 text-sm text-text-secondary">{children}</p>; }
function formatMoney(amount: number, currency: string) { const formatter = new Intl.NumberFormat("en", { style: "currency", currency }); return formatter.format(amount / 10 ** (formatter.resolvedOptions().maximumFractionDigits ?? 2)); }

